### ISSUE TITLE
Tambah Kejadian

### ISSUE THREAD

**Issue by mf4dl1** [geoenvo/opendims#9]
# User Interface
![image](https://cloud.githubusercontent.com/assets/4919662/13034932/199c455c-d375-11e5-8c46-364438d67b07.png)

**Comment by senoadiw** [comment]
@mf4dl1 untuk informasi batas wilayah kota, kecamatan, kelurahan, rw, ada di database yang dipakai jaksafe sekarang ya? Mungkin akan ada apps "Geolevel" di dalam opendims yang akan memanage data tersebut.

**Comment by mf4dl1** [comment]
Mia punya versi shapfile & postgisnya untuk administrasi dan asset. 
Pengelolaan Administrasi Boundary ada di #3  > Settings > Boundary
Nanti akan gw buatkan UI nya.
